### PR TITLE
Added support for MySQL provider

### PR DESCRIPTION
**Pull request by olegrumiancev**
Hi there! 

Great extension and exactly what I was looking for... Until I realized this is only working with MSSQL provider! Well, since today is my first day back from vacation and people are giving me some space I took the time to hopefully enhance this great extension with MySQL provider support, which will hopefully be helpful to folks like me where I have to work with both MS SQL and MySQL databases hosted in Azure.

I tried to follow your coding practices while also added some enhancements in a few places (such as separating Delete SQL texts out of sqlUtils into its own file due to it now requiring a little bit more logic)

Let me know if this works for you, or you'd like me to change anything

Best,
Oleg

### CODE REVIEW

**Comment by pacoweb** [comment]
@olegrumiancev, it look very nice! I will try to test the pull request today or tomorrow. Thank you!

**Comment by pacoweb** [comment]
@olegrumiancev , I have to ask you something in case it's a problem. It is regarding the **publisher** attribute of the package.json. I have no problem adding mentions to your work in the Release, in the project's Readme, etc. but I think that the publisher is not an attribute to indicate to the project collaborators or contributors
[https://code.visualstudio.com/api/working-with-extensions/publishing-extension#create-a-publisher](url)

**Comment by olegrumiancev** [comment]
No problem from my side! Would you like me to add a commit removing that,
or are you OK to make another commit yourself after the PR merge?

**Comment by pacoweb** [comment]
@olegrumiancev I´ll make the commit after merge your pull request. Thanks

**Comment by olegrumiancev** [comment]
Thank you for accepting the PR, happy to have contributed

**Pull request merged**
